class UrlNotFoundException implements Exception {}
class ResponseErrorException implements Exception {}
class ImageNotFoundException implements Exception {}
class ModelNotFoundException implements Exception {}
class PathNotFoundException implements Exception {}
class CouldNotEncodeException implements Exception {}
class CouldNotDecodeException implements Exception {}
class CouldNotFetchDataException implements Exception {}  
class ApiKeyNotFoundException implements Exception {}   