// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcMTSA7NdaLB_dHY5yufdv3ARxyX-1HvE',
    appId: '1:679181390627:web:40a876cad178564011b296',
    messagingSenderId: '679181390627',
    projectId: 'moviesapp-fd19a',
    authDomain: 'moviesapp-fd19a.firebaseapp.com',
    storageBucket: 'moviesapp-fd19a.appspot.com',
    measurementId: 'G-3BBE0P9GZM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALSJqLye8CPG_9MhTkjtWC7jkyWl4kruE',
    appId: '1:679181390627:android:44f2ad2e2174d8db11b296',
    messagingSenderId: '679181390627',
    projectId: 'moviesapp-fd19a',
    storageBucket: 'moviesapp-fd19a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPfV4guYhSON4d9pUqjnZbJcomzvf_9OM',
    appId: '1:679181390627:ios:30d6dca094c1fdfb11b296',
    messagingSenderId: '679181390627',
    projectId: 'moviesapp-fd19a',
    storageBucket: 'moviesapp-fd19a.appspot.com',
    iosBundleId: 'com.example.movies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPfV4guYhSON4d9pUqjnZbJcomzvf_9OM',
    appId: '1:679181390627:ios:216a247c25258b7111b296',
    messagingSenderId: '679181390627',
    projectId: 'moviesapp-fd19a',
    storageBucket: 'moviesapp-fd19a.appspot.com',
    iosBundleId: 'com.example.movies.RunnerTests',
  );
}
